const companyIcoSvg = [
	"airbnb-svgrepo-com.svg",
	"amazon-svgrepo-com.svg",
	"apple-svgrepo-com.svg",
	"behance-svgrepo-com.svg",
	"codeberg-svgrepo-com.svg",
	"dev-to-svgrepo-com.svg",
	"digitalocean-svgrepo-com.svg",
	"discord-svgrepo-com.svg",
	"docker-svgrepo-com.svg",
	"dropbox-svgrepo-com.svg",
	"ea-svgrepo-com.svg",
	"ebay-svgrepo-com.svg",
	"facebook-svgrepo-com.svg",
	"github-svgrepo-com.svg",
	"hp-svgrepo-com.svg",
	"intel-svgrepo-com.svg",
	"linkedin-svgrepo-com.svg",
	"microsoft-svgrepo-com.svg",
	"paypal-svgrepo-com.svg",
	"redhat-svgrepo-com.svg",
	"snapchat-svgrepo-com.svg",
	"steam-svgrepo-com.svg",
	"twitter-svgrepo-com.svg",
	"uber-svgrepo-com.svg",
	"ubisoft-svgrepo-com.svg",
	"wordpress-svgrepo-com.svg",
	"codeberg-svgrepo-com.svg",
	"auth0-svgrepo-com.svg",
];

export default companyIcoSvg;
